name: maxima
version: 5.40post
summary: A full-fledged computer algebra system
description: |
  A full featured computer algebra system,
  doing symbolic manipulation of polynomials, matrices, rational
  functions, integration, Todd-coxeter, graphing, bigfloats.  It has a
  symbolic debugger source level debugger for maxima code.  Maxima is
  based on the original Macsyma developed at MIT in the 1970's.
  It comes with extensive self tests.

grade: stable
confinement: strict
icon: interfaces/xmaxima/maxima-new.svg
 
apps:
  maxima:
    command: maxima
    plugs:
     - network
     - network-bind
     - home
     - removable-media
     - optical-drive

  rmaxima:
    command: rmaxima
    plugs:
     - network
     - network-bind
     - home
     - removable-media
     - optical-drive

  xmaxima:
    command: xmaxima
    plugs:
     - network
     - home
     - removable-media
     - optical-drive
#    desktop: usr/share/applications/xmaxima.desktop

parts:
  maxima:
    plugin: autotools
    source: .
    configflags:
     - --enable-sbcl
     - --enable-clisp
    build-packages:
     - sbcl
     - clisp
     - texinfo
     - libreadline-dev
     - locales
     - automake
     - autoconf
     - gawk
     - texlive-latex-recommended
     - tex-common
     - python
    stage-packages:
     - sbcl
     - clisp
     - gnuplot